# Generated by Django 3.2.9 on 2021-12-27 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideeProflie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('profilepic', models.ImageField(default='media/profilepic.png', upload_to='media/')),
                ('address', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=225, null=True)),
                ('invited_by', models.ManyToManyField(blank=True, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('userrelation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
