# Generated by Django 3.2.9 on 2022-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(max_length=225)),
                ('formContent', models.TextField()),
            ],
            options={
                'db_table': 'FormsTable',
            },
        ),
        migrations.CreateModel(
            name='ResponsesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response', models.JSONField()),
            ],
            options={
                'db_table': 'response_table',
            },
        ),
        migrations.CreateModel(
            name='UserForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_user', models.CharField(max_length=225)),
                ('form_name', models.CharField(max_length=225)),
                ('form_description', models.TextField()),
                ('form_content', models.TextField()),
                ('has_files', models.BooleanField()),
                ('user_responses', models.ManyToManyField(to='userforms.ResponsesData')),
            ],
            options={
                'db_table': 'users_forms',
            },
        ),
    ]
