# Generated by Django 3.2.9 on 2022-01-31 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('customer_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('customer_added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('step_file', models.FileField(upload_to='documents')),
                ('file_add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('lead', models.CharField(max_length=12)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=225)),
                ('customerName', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('userFile', models.FileField(upload_to='userfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=225, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('profilepic', models.ImageField(default='media/profilepic.png', upload_to='media/')),
                ('address', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=225, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=12)),
                ('userrelation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(unique=True)),
                ('description', models.CharField(max_length=224)),
                ('instruction', models.TextField()),
                ('visibility', models.BooleanField(default=True)),
                ('download', models.BooleanField(default=False)),
                ('upload', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('project_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_template', to='stepautomationapp.projecttemplate')),
                ('step_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepautomationapp.documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=20)),
                ('lead', models.CharField(max_length=12)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='stepautomationapp.customers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('description', models.CharField(max_length=224)),
                ('instruction', models.TextField()),
                ('visibility', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
                ('step_file', models.FileField(upload_to='customer_stepfiles')),
                ('upload', models.BooleanField(default=False)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('customerworkflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerworkflow', to='stepautomationapp.customerworkflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=225)),
                ('countryrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepautomationapp.country')),
            ],
        ),
    ]
