# Generated by Django 3.2.9 on 2022-01-28 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='stepfiles'),
            preserve_default=False,
        ),
    ]
