# Generated by Django 3.2.9 on 2021-12-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='step_document',
            new_name='step_file',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='file',
            new_name='step_file',
        ),
    ]
