# Generated by Django 3.2.9 on 2021-12-23 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersteps',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
