# Generated by Django 3.2.9 on 2021-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0002_auto_20211209_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
