# Generated by Django 3.2.9 on 2021-12-21 15:29

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0002_auto_20211221_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
