# Generated by Django 3.2.9 on 2021-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0002_customersteps_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='company',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profilepic',
            field=models.ImageField(default='media/profilepic.png', upload_to='media/avtars/'),
        ),
    ]
