# Generated by Django 3.2.9 on 2021-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0003_alter_steps_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
