# Generated by Django 3.2.9 on 2021-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0003_auto_20211225_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilepic',
            field=models.ImageField(default='media/profilepic.png', upload_to='media/'),
        ),
    ]
