# Generated by Django 3.2.9 on 2021-12-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0004_alter_projecttemplate_internal_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='internal_note',
        ),
    ]
