# Generated by Django 3.2.9 on 2021-12-25 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stepautomationapp', '0004_alter_userdata_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='userrelation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
