# Generated by Django 3.2.9 on 2021-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0005_remove_projecttemplate_internal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='lead',
            field=models.CharField(choices=[('GUIDE', 'Guide'), ('GUIDEE', 'Guidee'), ('BACK OFFICE', 'Backoffice')], max_length=12),
        ),
    ]
