# Generated by Django 3.2.9 on 2021-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0006_alter_projecttemplate_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='lead',
            field=models.CharField(max_length=12),
        ),
    ]
