# Generated by Django 3.2.9 on 2021-12-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0007_alter_projecttemplate_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='apostille',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='notarize',
        ),
    ]
