# Generated by Django 3.2.9 on 2021-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0008_auto_20211218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='count',
            field=models.FloatField(),
        ),
    ]
