# Generated by Django 3.2.9 on 2021-12-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0008_alter_userdata_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='company',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
