# Generated by Django 3.2.9 on 2021-12-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0009_alter_steps_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
