# Generated by Django 3.2.9 on 2021-12-26 09:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0009_alter_userdata_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
