# Generated by Django 3.2.9 on 2021-12-19 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stepautomationapp', '0010_auto_20211218_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=15)),
                ('customer', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('lead', models.CharField(max_length=12)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('description', models.CharField(max_length=224)),
                ('instruction', models.TextField()),
                ('visibility', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
                ('step_file', models.FileField(upload_to='customer_stepfiles')),
                ('upload', models.BooleanField(default=False)),
                ('customerworkflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerworkflow', to='stepautomationapp.customerworkflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
