# Generated by Django 3.2.9 on 2021-12-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0010_alter_userdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
