# Generated by Django 3.2.9 on 2021-12-19 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0011_customersteps_customerworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerworkflow',
            name='Status',
        ),
        migrations.AddField(
            model_name='customerworkflow',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
