# Generated by Django 3.2.9 on 2021-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0012_auto_20211219_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerworkflow',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
